version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi
    command: uvicorn --factory src.main:create_app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./src:/code/src
    depends_on:
      - db
    networks:
      - custom

  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - ./db_docker:/bitnami/postgresql
      - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
    ports:
      - "${PORT}:${PORT}"
    environment:
      - POSTGRES_USERNAME=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - custom

networks:
  custom:
    driver: bridge


