version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi
    command: >
      sh -c "while !! nc -z db 5432; do sleep 1; done 
      && alembic upgrade head
      && uvicorn --factory src.main:create_app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/code/src
    depends_on:
      - db
      - redis
    networks:
      - custom

  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - .postgres_volume_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - custom

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - .redis_volume_data:/data
    environment:
      - REDIS_PORT=6379
      - REDIS_DB=0
    networks:
      - custom

networks:
  custom:
    driver: bridge


